AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Join DCV instance to NIS Server and start a user session. Create SSM document,
  IAM Role, SSM doc and EC2 Instance. Attaches EC2 instance to AD.
Parameters:
  AMI:
    Type: String
    Default: ami-01290162cfb12929c
    Description: DCV AMI available in your region
  KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: KeyPair for EC2 Instance
  PublicSubnet:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-0d2184351e31500df
    Description: Subnet to place instance in
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-00073949a1ea2695e
    Description: VPC to place instance in
  InstanceType:
    Type: String
    Default: c5.xlarge
  NISDomainname:
    Type: String
    Description: NIS Domainname. Eg. hpc
  NISServer:
    Type: String
    Default: hpc
    Description: NIS Server IP. Eg. 10.0.0.142
  DCVUser:
    Type: String
    Description: User to create session. Eg. user1
  DCVELBListener:
    Type: String
    Default: >-
      arn:aws-cn:elasticloadbalancing:cn-northwest-1:079671731889:listener/app/dcv-elb/fe4b6334ff912b4e/80e20e242d3d4b73
    Description: 'Arn of ELB Listener. Eg. arn:...'
  SecurityGroupId:
    Type: String
    Default: sg-00349e21f93852083
    Description: Security Group Id for this DCV host
Resources:
  myEC2InstanceDCV:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyPair
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      HibernationOptions:
        Configured: true
      Tags:
        - Key: Name
          Value: DCV-Nis
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            VolumeType: gp2
            Encrypted: true
            VolumeSize: 30
            SnapshotId: snap-045221bd243931c71
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/sh -xe
            - |
              # System Update.
            - |
             

              sed -i "s|#web-url-path=\"/dcv\"|web-url-path=\"/`hostname -s`\"|" /etc/dcv/dcv.conf 
            - >
              sed -i "s|#authentication=\"none\"|authentication=system|"
              /etc/dcv/dcv.conf 
            - |
              systemctl restart dcvserver 
            - 'if [ ! -d "/home/"'
            - !Ref DCVUser
            - |2
               ]; then 
            - cp -rfp /etc/skel /home/
            - !Ref DCVUser
            - |2
               
            - 'chown -Rv '
            - !Ref DCVUser
            - ':'
            - !Ref DCVUser
            - ' /home/'
            - !Ref DCVUser
            - |2
               
            - |
              fi 
            - |
              sleep 5
            - |
              # Start DCV Session. 
            - 'dcv create-session --owner  '
            - !Ref DCVUser
            - |2
               default 
            - |+

  DCVTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Join 
        - ''
        - - /ip-
          - !Join 
            - '-'
            - !Split 
              - .
              - !GetAtt 
                - myEC2InstanceDCV
                - PrivateIp
          - '/#default'
      HealthCheckPort: 8443
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Name: !Join 
        - ''
        - - dcv-tg-ip-
          - !Join 
            - '-'
            - !Split 
              - .
              - !GetAtt 
                - myEC2InstanceDCV
                - PrivateIp
      Port: 8443
      Protocol: HTTPS
      TargetType: instance
      Targets:
        - Id: !Ref myEC2InstanceDCV
          Port: 8443
      UnhealthyThresholdCount: 2
      VpcId: !Ref VPC
  ListenerRule1:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref DCVTargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - !Join 
                - ''
                - - /ip-
                  - !Join 
                    - '-'
                    - !Split 
                      - .
                      - !GetAtt 
                        - myEC2InstanceDCV
                        - PrivateIp
                  - /*
      ListenerArn: !Ref DCVELBListener
      Priority: !Select 
        - 3
        - !Split 
          - .
          - !GetAtt 
            - myEC2InstanceDCV
            - PrivateIp
